version: '3'

services:
  app:
    build: .
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: sistemaencuestas
      DB_USER: postgres
      DB_PASSWORD: mysecretpassword
      MONGO_URL: mongodb://mongo:27017
      MONGO_NAME : sistemaEncuestas
      REDIS_HOST: cache
      REDIS_PORT: 6379
    ports:
      - 3000:3000
    networks:
      - web
    depends_on:
      - db
      - cache
      - mongo

    volumes:
      - .:/usr/src/app
    command: npm start
  test:
    build: .
    ports:
      - 5000:5000
    networks:
      - web
    depends_on:
      - app 
      - db
      - cache
      - mongo
    volumes:
      - .:/usr/src/app
    command: npm test

  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    networks:
      - web
    volumes:
      - ./database/:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
    

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: sistemaEncuestas
    networks:
      - web
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  cache:
    image: redis:latest
    restart: always
    volumes:
      - "./.data:/data"
    ports:
      - '6379:6379'
    networks:
      - web
  
networks:
  web:
    driver: bridge
