version: '3'

services:
  app:
    build: .
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: sistemaencuestas
      DB_USER: postgres
      DB_PASSWORD: mysecretpassword
      MONGO_URL: mongodb://mongo:27017
      MONGO_NAME : sistemaEncuestas
      REDIS_HOST: cache
      REDIS_PORT: 6379
      REDIS_PASSWORD: mysecretpassword
    ports:
      - 3000:3000
    networks:
      - web
    depends_on:
      - db
      - cache
    volumes:
      - .:/usr/src/app
    command: npm start

  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    networks:
      - web
    volumes:
      - ./database/:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
    
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@tech.com
      PGADMIN_DEFAULT_PASSWORD: 1234
    ports:
      - 5050:80
    networks:
      - web

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: sistemaEncuestas
    networks:
      - web
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    networks:
      - web
    depends_on:
      - mongo
  
  cache:
    image: redis:6-alpine
    restart: always
    volumes:
      - "./.data:/data"
    ports:
      - '6379:6379'
    command: 
      redis-server --save 20 1 --loglevel warning --requirepass mysecretpassword
    networks:
      - web
  
networks:
  web:
    driver: bridge
