name: Docker Build and Test

on:
  push:
    branches:
      - main
      - tests
  pull_request:
    branches:
      - main
      - tests

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      run: |
        docker build -t javialroro/snupieencuestas:latest .
      
    - name: Push Docker Image
      run: |
        docker push javialroro/snupieencuestas:latest

    - name: Docker Compose
      run: |
        docker compose up -d

    - name: Stop Docker Compose
      run: |
        docker-compose down
        
    - name: Check Test Result
      run: |
        if [ "${{ steps.install_dependencies_and_run_tests.outcome }}" != "success" ]; then
          echo "Tests failed, cancelling merge."
          exit 1
        fi
